server:
  port: 8080
spring:
  application:
    name: flowable
  datasource:
    url: jdbc:mysql://192.168.13.170:3306/flowable?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowMultiQueries=true&nullCatalogMeansCurrent=true
    username: root
    password: Root!@#
    driver-class-name: com.mysql.cj.jdbc.Driver
flowable:
  #关闭定时任务JOB
  async-executor-activate: false
  #将databaseSchemaUpdate设置为true。当Flowable发现库与数据库表结构不一致时，会自动将数据库表结构升级至新版本。
  database-schema-update: false
  #流程字体
  activityFontName: \u5B8B\u4F53
  labelFontName: \u5B8B\u4F53
  annotationFontName: \u5B8B\u4F53
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: false

mybatis:
  mapper-locations: classpath:mapper/*.xml,classpath:/META-INF/modeler-mybatis-mappings/*.xml
  configuration-properties:
    prefix:
    blobType: BLOB
    boolValue: TRUE
